version: '3'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=encodingdb
    ports:
      - "5432:5432"
  
  web:
    build: .
    command: >
      bash -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=encodingdb
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=password123

volumes:
  postgres_data: